package io.github.kiyohitonara.biwa.domain.model

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

/**
 * Represents a user-defined album that can hold any number of media items.
 *
 * Albums form a tree: [parentId] references the containing album, or is null for a
 * root-level album. Media membership is direct only and is never rolled up to ancestors.
 */
@OptIn(ExperimentalObjCName::class)
@ObjCName("MediaAlbum")
data class Album(
    /** Unique identifier generated by the app (UUID). */
    val id: String,
    /** Display name of the album. */
    val name: String,
    /** Timestamp when this album was created (Unix epoch seconds). */
    val createdAt: Long,
    /** ID of the containing album, or null for a root-level album. */
    val parentId: String? = null,
)
