package io.github.kiyohitonara.biwa.domain.model

/** Represents a media file managed in the Biwa library. */
data class MediaItem(
    /** Unique identifier generated by the app (UUID). */
    val id: String,
    /** Absolute path to the copied file in app-internal storage. */
    val filePath: String,
    /** Type of the media file. */
    val mediaType: MediaType,
    /** Display name derived from the original file name. */
    val displayName: String,
    /** Total playback duration in milliseconds. Null for photos. */
    val durationMs: Long?,
    /** Width in pixels. */
    val widthPx: Long?,
    /** Height in pixels. */
    val heightPx: Long?,
    /** File size in bytes. */
    val fileSizeBytes: Long?,
    /** Path to the cached thumbnail file. */
    val thumbnailPath: String?,
    /** Capture or creation timestamp (Unix epoch seconds). */
    val takenAt: Long?,
    /** Order value for manual sorting. Smaller values appear first. */
    val sortOrder: Long,
    /** Timestamp of the last time this item was viewed (Unix epoch seconds). */
    val lastViewedAt: Long?,
    /** Timestamp when this item was added to the library (Unix epoch seconds). */
    val addedAt: Long,
)
